### ISSUE TITLE
whitelist for stripFragment and maybe add stripQuery and whitelist for this

### ISSUE THREAD

**Issue by evilebottnawi** [ben-eb/postcss-normalize-url#8]
i need some hash and query save, other remove

**Comment by ben-eb** [comment]
Can you describe this request in a bit more detail please? Expected input/output CSS, API etc.

**Comment by evilebottnawi** [comment]
@ben-eb 
My code (from https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css):
```css
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.5.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.5.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.5.0') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.5.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.5.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.5.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
I don't need `?v=4.5.0`.  I think be cool add an option to delete this (`stripQuery`). Also add `stripQueryWhitelist` options contain not removed some query params. Also it would be nice to have `stripFragmentWhitelist` (I think it needs a separate issue).
